### PR TITLE
chore: upgrade LiveView dependency

### PR DESCRIPTION
**Pull request by andyl**
Upgrade LiveView dependency from 0.20 to 1.0.

### CODE REVIEW

**Comment by mhanberg** [comment]
can you make sure the heex template outputs markup that is already correctly formatted with regard to the new curly brace syntax?

**Comment by andyl** [comment]
I've tried two sites with the 'curly brace' syntax: 
1. my own website ([example page](https://github.com/andyl/xmeyers/blob/master/lib/xmeyers/pages/maps_page.ex))
2. simple test with a 'tableau.new' generated site: 
```elixir
defmodule Tango.HomePage do
  use Tableau.Page,
    layout: Tango.RootLayout,
    permalink: "/"

  use Phoenix.Component

  def template(assigns) do
    assigns = Map.merge(assigns, %{msg: "HI"})
    ~H"""
    <p>
      hello {@msg} world!
    </p>
    """
  end
end
```

Haven't seen any problems so far.

LMK if you'd like more test cases, etc.

**Comment by mhanberg** [comment]
Sorry, I just meant, make sure that the generated site is fully formatted, not that the new syntax works in general.

**Comment by andyl** [comment]
Site formatting looks good.  The generated site is just 'hello world' - not much styling.  The generated styles for my own website look fine.  I tried this on 1.17.3 and 1.18.0.

**Pull request merged**
